import streamlit as st
from app.ai_agent import generate_sql_from_user_input
from app.db import safe_execute_query
from app.utils import log_interaction

##st.title("DFS Football AI Agent")
st.set_page_config(page_title="AI Fantasy Football Data Agent", page_icon="🤖", layout="wide")


st.title("🤖 AI Fantasy Football Data Agent")
st.markdown("### Ask questions about your fantasy football and DFS data!")

with st.expander("📘 About this Agent"):
    st.markdown("""
    This AI Agent is connected to a **PostgreSQL fantasy football database** and can:
    - Query weekly player stats from 2025 and DFS lineup data for past weeks and the current week
    - Perform joins, aggregations, and simple analyses
    - Shows the query performed
    - Returns a data table
    
    **Example questions:**
    - “Who were the top 5 WRs by fantasy points last week?”
    - “Which teams were the worst against running backs on average?”
    - Can I get the top 10 players (no qbs) by their current week salary/ avg opportunities the last 3 weeks?  Make sure their avg is > 1 and the lower the better!
    """)

st.divider()

user_query = st.text_area("Ask a question about your DFS data:")



if st.button("Run AI Query") and user_query.strip():
    try:
        sql_query = generate_sql_from_user_input(user_query)
        if not sql_query:
            st.error("No SQL generated by the model.")
        else:
            st.subheader("Generated SQL")
            st.code(sql_query)

            try:
                df = safe_execute_query(sql_query)
                st.subheader("Results")
                st.dataframe(df)
            except Exception as e:
                log_interaction(user_query + " sql query: " + sql_query, f"Blocked query: {e}, safety_check")
                st.error(f"Query failed safety check: {e}")

    except Exception as e:
        st.error(f"Something went wrong: {e}")


st.divider()
st.subheader("📬 Contact")
st.markdown("""
**Gary Bolduc**  
💼 Data Analyst | AI Enthusiast
🌐 [www.garybolduc.com](https://www.garybolduc.com)  
🔗 [LinkedIn](https://www.linkedin.com/in/garybolduc) | [GitHub](https://github.com/garybolduc)
""")
